In [3]:
import pandas as pd
import numpy as np

# Cleaning Data

****
### Handling Missing Values

In [4]:
df= pd.read_csv("raw_data.csv")

df.isnull() #gives true where there is null value
df.isna() #same as isnull()
df.isnull().sum() #to count how many null values are there
df.dropna() #to drop all rows with null values
df.dropna(axis=1) #to drop all column with null values
df.fillna(0) #to fill null values with smth
df["age"]=df["age"].fillna(df["age"].mean())

df.ffill() #forward fill
df.bfill() #backword fill

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  51000.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6    Ahmed Khan  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     USA     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

### Handle duplicate values

In [5]:
df = pd.read_csv("raw_data.csv") 

df.duplicated()                      # True for duplicate rows
df.duplicated("country")             # True for duplicate rows in particular col
df.duplicated(["country", "gender"]) 

df.drop_duplicates()                 # drops duplicate rows

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

### Handle data types

In [6]:
df = pd.read_csv("raw_data.csv") 

df.dtypes                                     # dtype of each col
df2 = df.fillna(0).copy()
df2["income"] = df2["income"].astype(int)       # change dtype

#String types
df2["country"].str.lower() #lowers case
df2["country"].str.upper() #uppers case
df2["country"].str.capitalize() #capitalizes words
df2["country"].str.strip() #strips space
df2["name"].str.split(" ") #splits words
df2["country"].str.contains("US") #gives true or false based on if smth exists
df2["country"].str.contains("india", case=False) #in case upper or lower doesn't matter

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

### Transformation/Feature Engineering

In [16]:
df2=df2.copy() #to make a copy
#applying a function on a row or column 
df2["Tax"]=df2["income"].apply(lambda x: "10%" if x <6000 else "20%") #lambda makes function in a single line if x<6000 then tax is 10% otherwise 20%
df2
#map values to other
new_gender_values = {
    "Male" : "M",
    "Female": "F",
    "Unknown" : "U"}
df2["gender"]=df2["gender"].map(new_gender_values)
df2
#assign some new values
df2.assign(new_income=df2["income"] * 1.1) #1.1 means increase by 10%

#replace specific values
df2["country"].replace("USA","United States")

0     United States
1     United States
2            Canada
3     United States
4             Spain
5             China
6             India
7                 0
8     United States
9            Mexico
10    United States
Name: country, dtype: object

### Transformation- Sorting

In [34]:
df2=df.copy()

#Renaming

df2.columns= ["Id","Name","Age","Country","Gender","Income","Tax"]
df2.rename(columns={"Income":"Salary"})
df2.rename(index={0:"first"})

#Sorting-Values & index
df2.sort_values("Income") #in ascending
df2.sort_values("Income", ascending=False) #in descending
df2.sort_values(["Age","Income"]) #sorts on basis of age and if age is same then sorts on basis of income
sorted_df2 =df2.sort_values(["Age","Income"]) #sorts values but not index
sorted_df2.sort_index() #sorts index but values aren't sorted

#Reset Index- sorts both index and value
sorted_df2.reset_index()
sorted_df2.reset_index(drop=True) #to drop original value

#Ranking
df2["Ranking"] = df2["Income"].rank(ascending=False,method="dense") #by dense method same income values get same rank 
#while in default method it gives average rank and in min method it skips next rank 

#Reorder
df2[["Id", "Name", "Age", "Income","Tax", "Gender", "Country", "Ranking"]]

    Id          Name   Age   Income  Tax   Gender Country  Ranking
0    1      John Doe  29.0  55000.0  20%     Male     USA      5.0
1    1      John Doe  29.0  55000.0  20%     Male     USA      5.0
2    2    Jane Smith   NaN  62000.0  20%   Female  Canada      3.0
3    3          Alex   NaN  47000.0  20%  Unknown     USA      7.0
4    4  Maria Garcia  34.0      NaN  20%   Female   Spain      NaN
5    5        Li Wei  27.0  51000.0  20%     Male   China      6.0
6    6           NaN  45.0  73000.0  20%   Female   India      1.0
7    7    Ahmed Khan  38.0  68000.0  20%     Male     NaN      2.0
8    8    Rachel Lee  29.0  62000.0  20%   Female     USA      3.0
9    9   Carlos Ruiz   NaN  45000.0  20%     Male  Mexico      8.0
10  10   Emily Davis  31.0  58000.0  20%      NaN     USA      4.0

In [43]:
#shift id column to end
df2=df.copy()

new_col_order=[col for col in df.columns if col!="id"] + ["id"]
df2[new_col_order]

            name   age country   gender   income  Tax  id
0       John Doe  29.0     USA     Male  55000.0  20%   1
1       John Doe  29.0     USA     Male  55000.0  20%   1
2     Jane Smith   NaN  Canada   Female  62000.0  20%   2
3           Alex   NaN     USA  Unknown  47000.0  20%   3
4   Maria Garcia  34.0   Spain   Female      NaN  20%   4
5         Li Wei  27.0   China     Male  51000.0  20%   5
6            NaN  45.0   India   Female  73000.0  20%   6
7     Ahmed Khan  38.0     NaN     Male  68000.0  20%   7
8     Rachel Lee  29.0     USA   Female  62000.0  20%   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0  20%   9
10   Emily Davis  31.0     USA      NaN  58000.0  20%  10

### Writing to csv files

In [47]:
df = pd.read_csv("raw_data.csv")

df2= df.copy()

df2.drop_duplicates(inplace=True)  #inplace means to change in original df
df2.sort_values("income",inplace=True)

df.to_csv("sorted_data.csv") #save df as a csv file
df.to_csv("sorted_data.csv", index=False) #removes index
json_string = df.to_json() #converts to json
print(json_string)

{"id":{"0":1,"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10},"name":{"0":"John Doe","1":"John Doe","2":"Jane Smith","3":"Alex","4":"Maria Garcia","5":"Li Wei","6":null,"7":"Ahmed Khan","8":"Rachel Lee","9":"Carlos Ruiz","10":"Emily Davis"},"age":{"0":29.0,"1":29.0,"2":null,"3":null,"4":34.0,"5":27.0,"6":45.0,"7":38.0,"8":29.0,"9":null,"10":31.0},"country":{"0":"USA","1":"USA","2":"Canada","3":"USA","4":"Spain","5":"China","6":"India","7":null,"8":"USA","9":"Mexico","10":"USA"},"gender":{"0":"Male","1":"Male","2":"Female","3":"Unknown","4":"Female","5":"Male","6":"Female","7":"Male","8":"Female","9":"Male","10":null},"income":{"0":55000.0,"1":55000.0,"2":62000.0,"3":47000.0,"4":null,"5":51000.0,"6":73000.0,"7":68000.0,"8":62000.0,"9":45000.0,"10":58000.0}}

### Grouping & Aggregation

In [67]:
df2=df.copy()

df2.groupby("country")["income"].mean() #gives mean of income acc to country

df2.groupby("gender")["income"].mean()  #mean of income acc to gender

df2.groupby("gender")["income"].max()  #max of income acc to gender

df2.groupby("gender")["income"].min()  #min of income acc to gender

df2.groupby("country")["gender"].count()   #count of gender acc to country

df2.groupby("country")["income"].agg(["mean","max","min"]) #uses aggregation to apply more than 1 property

df2.groupby("country")["income"].agg(avg_salary="mean",max_salary="max",min_salary="min") #gives name 

df2.groupby("country").agg({ #aggregate on multiple cols
    "age":"mean",
    "income":"max"
})
df2.groupby("country").agg(
    avg_age=("age","mean"),
    max_income=("income","max") #give them name
)

         avg_age  max_income
country
Canada       NaN     62000.0
China       27.0     51000.0
India       45.0     73000.0
Mexico       NaN     45000.0
Spain       34.0         NaN
USA         29.5     62000.0