In [1]:
import pandas as pd
import numpy as np

# Cleaning Data

****
### Handling Missing Values

In [10]:
df= pd.read_csv("raw_data.csv")

df.isnull() #gives true where there is null value
df.isna() #same as isnull()
df.isnull().sum() #to count how many null values are there
df.dropna() #to drop all rows with null values
df.dropna(axis=1) #to drop all column with null values
df.fillna(0) #to fill null values with smth
df["age"]=df["age"].fillna(df["age"].mean())

df.ffill() #forward fill
df.bfill() #backword fill

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  51000.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6    Ahmed Khan  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     USA     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

### Handle duplicate values

In [11]:
df = pd.read_csv("raw_data.csv") 

df.duplicated()                      # True for duplicate rows
df.duplicated("country")             # True for duplicate rows in particular col
df.duplicated(["country", "gender"]) 

df.drop_duplicates()                 # drops duplicate rows

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

### Handle data types

In [24]:
df = pd.read_csv("raw_data.csv") 

df.dtypes                                     # dtype of each col
df2 = df.fillna(0).copy()
df2["income"] = df2["income"].astype(int)       # change dtype

#String types
df2["country"].str.lower() #lowers case
df2["country"].str.upper() #uppers case
df2["country"].str.capitalize() #capitalizes words
df2["country"].str.strip() #strips space
df2["name"].str.split(" ") #splits 
df2["country"].str.contains("US")
df2["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object